export const MVS_TOKEN_ADDRESS = '0x98afac3b663113d29dc2cd8c2d1d14793692f110'
export const BUY_NFT_URL = 'https://app.mvscoin.org/nfts'
export const NFT_POOL_URL = 'https://app.mvscoin.org/nft-pool'
export const DOCS_URL = 'https://docs.mvscoin.org'
export const DAPP_URL = 'https://app.mvscoin.org'
export const CERTIK_URL = 'https://www.certik.com/projects/multiverse'
export const WHITE_PAPER_URL = 'https://mvscoin.org/whitepaper.pdf'
export const MARKET_URL = 'https://app.mvscoin.org/nfts'
